// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package base

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Adds one or more bases to the kustomization.yaml in current directory
func Base(filePath string, opts ...BaseOpt) *tools.CommandContext {
	options := &baseOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "add", "base")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, filePath)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type BaseOpt func(*baseOptions)

func SetToolProvider(p tools.ToolProvider) BaseOpt {
	return func(opts *baseOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) BaseOpt {
	return func(opts *baseOptions) {
		opts.ToolVersion = v
	}
}

// print a stack-trace on error
func StackTrace() BaseOpt {
	return func(opts *baseOptions) {
		opts.stackTrace = ptrhelpers.Bool(true)
	}
}

type baseOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	stackTrace   *bool
}

func (o *baseOptions) toArgs() []string {
	var renderedArgs []string

	if o.stackTrace != nil {
		renderedArgs = append(renderedArgs, "--stack-trace")
	}

	return renderedArgs
}
