// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package transformer

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Removes one or more transformers from kustomization.yaml
func Transformer(filePath string, opts ...TransformerOpt) *tools.CommandContext {
	options := &transformerOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "remove", "transformer")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, filePath)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// Removes one or more transformers from kustomization.yaml
func TransformerWithFilePaths(filePaths []string, opts ...TransformerOpt) *tools.CommandContext {
	options := &transformerOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "remove", "transformer")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, filePaths...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type TransformerOpt func(*transformerOptions)

func SetToolProvider(p tools.ToolProvider) TransformerOpt {
	return func(opts *transformerOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) TransformerOpt {
	return func(opts *transformerOptions) {
		opts.ToolVersion = v
	}
}

// print a stack-trace on error
func StackTrace() TransformerOpt {
	return func(opts *transformerOptions) {
		opts.stackTrace = ptrhelpers.Bool(true)
	}
}

type transformerOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	stackTrace   *bool
}

func (o *transformerOptions) toArgs() []string {
	var renderedArgs []string

	if o.stackTrace != nil {
		renderedArgs = append(renderedArgs, "--stack-trace")
	}

	return renderedArgs
}
