// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package namespace

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Sets the value of the namespace field in the kustomization file
func Namespace(namespace string, opts ...NamespaceOpt) *tools.CommandContext {
	options := &namespaceOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "set", "namespace")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, namespace)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type NamespaceOpt func(*namespaceOptions)

func SetToolProvider(p tools.ToolProvider) NamespaceOpt {
	return func(opts *namespaceOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) NamespaceOpt {
	return func(opts *namespaceOptions) {
		opts.ToolVersion = v
	}
}

type namespaceOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
}

func (o *namespaceOptions) toArgs() []string {
	var renderedArgs []string

	return renderedArgs
}
