// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/k3d.json

package delete

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/k3d"
)

// Delete cluster(s).
func Delete(opts ...DeleteOpt) *tools.CommandContext {
	options := &deleteOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "cluster", "delete")

	_args = append(_args, options.toArgs()...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// Delete cluster(s).
func DeleteWithName(name string, opts ...DeleteOpt) *tools.CommandContext {
	options := &deleteOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "cluster", "delete")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, name)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// Delete cluster(s).
func DeleteWithNames(names []string, opts ...DeleteOpt) *tools.CommandContext {
	options := &deleteOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "cluster", "delete")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, names...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type DeleteOpt func(*deleteOptions)

func SetToolProvider(p tools.ToolProvider) DeleteOpt {
	return func(opts *deleteOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) DeleteOpt {
	return func(opts *deleteOptions) {
		opts.ToolVersion = v
	}
}

// Delete all existing clusters
func All() DeleteOpt {
	return func(opts *deleteOptions) {
		opts.all = ptrhelpers.Bool(true)
	}
}

// Enable Log timestamps
func Timestamps() DeleteOpt {
	return func(opts *deleteOptions) {
		opts.timestamps = ptrhelpers.Bool(true)
	}
}

// Enable super verbose output (trace logging)
func Trace() DeleteOpt {
	return func(opts *deleteOptions) {
		opts.trace = ptrhelpers.Bool(true)
	}
}

// Enable verbose output (debug logging)
func Verbose() DeleteOpt {
	return func(opts *deleteOptions) {
		opts.verbose = ptrhelpers.Bool(true)
	}
}

type deleteOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	all          *bool
	timestamps   *bool
	trace        *bool
	verbose      *bool
}

func (o *deleteOptions) toArgs() []string {
	var renderedArgs []string

	if o.all != nil {
		renderedArgs = append(renderedArgs, "--all")
	}

	if o.timestamps != nil {
		renderedArgs = append(renderedArgs, "--timestamps")
	}

	if o.trace != nil {
		renderedArgs = append(renderedArgs, "--trace")
	}

	if o.verbose != nil {
		renderedArgs = append(renderedArgs, "--verbose")
	}

	return renderedArgs
}
