// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package annotation

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Sets one or more commonAnnotations in kustomization.yaml
func Annotation(annotation string, opts ...AnnotationOpt) *tools.CommandContext {
	options := &annotationOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "set", "annotation")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, annotation)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type AnnotationOpt func(*annotationOptions)

func SetToolProvider(p tools.ToolProvider) AnnotationOpt {
	return func(opts *annotationOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) AnnotationOpt {
	return func(opts *annotationOptions) {
		opts.ToolVersion = v
	}
}

type annotationOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
}

func (o *annotationOptions) toArgs() []string {
	var renderedArgs []string

	return renderedArgs
}
