// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/k3d.json

package get

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/k3d"
)

// Print kubeconfig(s) from cluster(s).
func Get(opts ...GetOpt) *tools.CommandContext {
	options := &getOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "kubeconfig", "get")

	_args = append(_args, options.toArgs()...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// Print kubeconfig(s) from cluster(s).
func GetWithCluster(cluster string, opts ...GetOpt) *tools.CommandContext {
	options := &getOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "kubeconfig", "get")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, cluster)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// Print kubeconfig(s) from cluster(s).
func GetWithClusters(clusters []string, opts ...GetOpt) *tools.CommandContext {
	options := &getOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "kubeconfig", "get")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, clusters...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type GetOpt func(*getOptions)

func SetToolProvider(p tools.ToolProvider) GetOpt {
	return func(opts *getOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) GetOpt {
	return func(opts *getOptions) {
		opts.ToolVersion = v
	}
}

// Output kubeconfigs from all existing clusters
func All() GetOpt {
	return func(opts *getOptions) {
		opts.all = ptrhelpers.Bool(true)
	}
}

// Enable Log timestamps
func Timestamps() GetOpt {
	return func(opts *getOptions) {
		opts.timestamps = ptrhelpers.Bool(true)
	}
}

// Enable super verbose output (trace logging)
func Trace() GetOpt {
	return func(opts *getOptions) {
		opts.trace = ptrhelpers.Bool(true)
	}
}

// Enable verbose output (debug logging)
func Verbose() GetOpt {
	return func(opts *getOptions) {
		opts.verbose = ptrhelpers.Bool(true)
	}
}

type getOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	all          *bool
	timestamps   *bool
	trace        *bool
	verbose      *bool
}

func (o *getOptions) toArgs() []string {
	var renderedArgs []string

	if o.all != nil {
		renderedArgs = append(renderedArgs, "--all")
	}

	if o.timestamps != nil {
		renderedArgs = append(renderedArgs, "--timestamps")
	}

	if o.trace != nil {
		renderedArgs = append(renderedArgs, "--trace")
	}

	if o.verbose != nil {
		renderedArgs = append(renderedArgs, "--verbose")
	}

	return renderedArgs
}
