// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/lefthook.json

package version

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/lefthook"
)

// Show lefthook version
func Version(opts ...VersionOpt) *tools.CommandContext {
	options := &versionOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "version")

	_args = append(_args, options.toArgs()...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(lefthook.LefthookToolInfo, defaults.String(options.ToolVersion, lefthook.DefaultToolVersion), options.ToolProvider, lefthook.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type VersionOpt func(*versionOptions)

func SetToolProvider(p tools.ToolProvider) VersionOpt {
	return func(opts *versionOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) VersionOpt {
	return func(opts *versionOptions) {
		opts.ToolVersion = v
	}
}

type versionOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
}

func (o *versionOptions) toArgs() []string {
	var renderedArgs []string

	return renderedArgs
}
