// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package edit

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Fix the missing fields in kustomization file
func Fix(opts ...FixOpt) *tools.CommandContext {
	options := &fixOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "fix")

	_args = append(_args, options.toArgs()...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type FixOpt func(*fixOptions)

func SetToolProvider(p tools.ToolProvider) FixOpt {
	return func(opts *fixOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) FixOpt {
	return func(opts *fixOptions) {
		opts.ToolVersion = v
	}
}

// Fix the missing fields in kustomization file
func Vars() FixOpt {
	return func(opts *fixOptions) {
		opts.vars = ptrhelpers.Bool(true)
	}
}

// print a stack-trace on error
func StackTrace() FixOpt {
	return func(opts *fixOptions) {
		opts.stackTrace = ptrhelpers.Bool(true)
	}
}

type fixOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	vars         *bool
	stackTrace   *bool
}

func (o *fixOptions) toArgs() []string {
	var renderedArgs []string

	if o.vars != nil {
		renderedArgs = append(renderedArgs, "--vars")
	}

	if o.stackTrace != nil {
		renderedArgs = append(renderedArgs, "--stack-trace")
	}

	return renderedArgs
}
