// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kubeconform.json

// A FAST Kubernetes manifests validator, with support for Custom Resources!
package kubeconform
