// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/goreleaser.json

package check

import (
	"fmt"

	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/goreleaser"
)

// Checks if configuration is valid
func Check(opts ...CheckOpt) *tools.CommandContext {
	options := &checkOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "check")

	_args = append(_args, options.toArgs()...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(goreleaser.GoReleaserToolInfo, defaults.String(options.ToolVersion, goreleaser.DefaultToolVersion), options.ToolProvider, goreleaser.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type CheckOpt func(*checkOptions)

func SetToolProvider(p tools.ToolProvider) CheckOpt {
	return func(opts *checkOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) CheckOpt {
	return func(opts *checkOptions) {
		opts.ToolVersion = v
	}
}

// Load configuration from file
func Config(value string) CheckOpt {
	return func(opts *checkOptions) {
		opts.config = &value
	}
}

type checkOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	config       *string
}

func (o *checkOptions) toArgs() []string {
	var renderedArgs []string

	if o.config != nil {
		renderedArgs = append(renderedArgs, "--config", fmt.Sprintf("%s", ptrhelpers.StringValue(o.config)))
	}

	return renderedArgs
}
