// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package kustomize

import (
	"errors"
	"os"
	"strings"

	"github.com/stephenwilliams/go-clitools/internal/versionproviders"
	"github.com/stephenwilliams/go-clitools/tools"
)

var KustomizeToolInfo = kustomizeToolInfo{}

type kustomizeToolInfo struct{}

func (kustomizeToolInfo) Name() string {
	return "kustomize"
}

func (kustomizeToolInfo) ExecutableName() string {
	return "kustomize"
}

// GetVersion returns the version for the tool found with the provided tool provider.
// If tp is nil, the default tool provider is used.
func (i kustomizeToolInfo) GetVersion(tp tools.ToolProvider) (string, error) {
	if tp != nil {
		// do nothing
	} else if DefaultToolProvider != nil {
		tp = DefaultToolProvider
	} else if tools.DefaultToolProvider != nil {
		tp = tools.DefaultToolProvider
	} else {
		return "", errors.New("no tool provider provided and defaults are nil")
	}

	path, err := tools.ResolveTool(KustomizeToolInfo, DefaultToolVersion, tp)
	if err != nil {
		return "", err
	}

	return i.GetVersionWithPath(path)
}

// GetVersionWithPath returns the version for the tool found with the provided path.
// to the tool
func (kustomizeToolInfo) GetVersionWithPath(path string) (string, error) {
	cmd := &tools.CommandContext{
		Args: []string{"version", "--short"},
		Path: path,
	}

	var b strings.Builder
	_, _, err := cmd.Exec(&b, os.Stderr)
	if err != nil {
		return "", err
	}

	v := b.String()

	v = versionproviders.SplitLine(v, 0)

	v = versionproviders.SplitString(v, " ", 0)

	v = strings.TrimPrefix(v, "{kustomize/v")

	v = strings.TrimSpace(v)

	return v, nil
}
