// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package resource

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Add the name of a file containing a resource to the kustomization file.
func Resource(filePath string, opts ...ResourceOpt) *tools.CommandContext {
	options := &resourceOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "add", "resource")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, filePath)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type ResourceOpt func(*resourceOptions)

func SetToolProvider(p tools.ToolProvider) ResourceOpt {
	return func(opts *resourceOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) ResourceOpt {
	return func(opts *resourceOptions) {
		opts.ToolVersion = v
	}
}

// print a stack-trace on error
func StackTrace() ResourceOpt {
	return func(opts *resourceOptions) {
		opts.stackTrace = ptrhelpers.Bool(true)
	}
}

type resourceOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	stackTrace   *bool
}

func (o *resourceOptions) toArgs() []string {
	var renderedArgs []string

	if o.stackTrace != nil {
		renderedArgs = append(renderedArgs, "--stack-trace")
	}

	return renderedArgs
}
