// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/k3d.json

package list

import (
	"fmt"

	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/k3d"
)

// List cluster(s)
func List(opts ...ListOpt) *tools.CommandContext {
	options := &listOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "cluster", "list")

	_args = append(_args, options.toArgs()...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// List cluster(s)
func ListWithName(name string, opts ...ListOpt) *tools.CommandContext {
	options := &listOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "cluster", "list")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, name)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// List cluster(s)
func ListWithNames(names []string, opts ...ListOpt) *tools.CommandContext {
	options := &listOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "cluster", "list")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, names...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type ListOpt func(*listOptions)

func SetToolProvider(p tools.ToolProvider) ListOpt {
	return func(opts *listOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) ListOpt {
	return func(opts *listOptions) {
		opts.ToolVersion = v
	}
}

// Disable headers
func NoHeaders() ListOpt {
	return func(opts *listOptions) {
		opts.noHeaders = ptrhelpers.Bool(true)
	}
}

// Output format. One of: json|yaml
func Output(value string) ListOpt {
	return func(opts *listOptions) {
		opts.output = &value
	}
}

// Enable Log timestamps
func Timestamps() ListOpt {
	return func(opts *listOptions) {
		opts.timestamps = ptrhelpers.Bool(true)
	}
}

// Enable super verbose output (trace logging)
func Trace() ListOpt {
	return func(opts *listOptions) {
		opts.trace = ptrhelpers.Bool(true)
	}
}

// Enable verbose output (debug logging)
func Verbose() ListOpt {
	return func(opts *listOptions) {
		opts.verbose = ptrhelpers.Bool(true)
	}
}

type listOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	noHeaders    *bool
	output       *string
	timestamps   *bool
	trace        *bool
	verbose      *bool
}

func (o *listOptions) toArgs() []string {
	var renderedArgs []string

	if o.noHeaders != nil {
		renderedArgs = append(renderedArgs, "--no-headers")
	}

	if o.output != nil {
		renderedArgs = append(renderedArgs, "--output", fmt.Sprintf("%s", ptrhelpers.StringValue(o.output)))
	}

	if o.timestamps != nil {
		renderedArgs = append(renderedArgs, "--timestamps")
	}

	if o.trace != nil {
		renderedArgs = append(renderedArgs, "--trace")
	}

	if o.verbose != nil {
		renderedArgs = append(renderedArgs, "--verbose")
	}

	return renderedArgs
}
