// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/go.json

package golang

import (
	"errors"
	"os"
	"strings"

	"github.com/stephenwilliams/go-clitools/internal/versionproviders"
	"github.com/stephenwilliams/go-clitools/tools"
)

var GoToolInfo = golangToolInfo{}

type golangToolInfo struct{}

func (golangToolInfo) Name() string {
	return "Go"
}

func (golangToolInfo) ExecutableName() string {
	return "go"
}

// GetVersion returns the version for the tool found with the provided tool provider.
// If tp is nil, the default tool provider is used.
func (i golangToolInfo) GetVersion(tp tools.ToolProvider) (string, error) {
	if tp != nil {
		// do nothing
	} else if DefaultToolProvider != nil {
		tp = DefaultToolProvider
	} else if tools.DefaultToolProvider != nil {
		tp = tools.DefaultToolProvider
	} else {
		return "", errors.New("no tool provider provided and defaults are nil")
	}

	path, err := tools.ResolveTool(GoToolInfo, DefaultToolVersion, tp)
	if err != nil {
		return "", err
	}

	return i.GetVersionWithPath(path)
}

// GetVersionWithPath returns the version for the tool found with the provided path.
// to the tool
func (golangToolInfo) GetVersionWithPath(path string) (string, error) {
	cmd := &tools.CommandContext{
		Args: []string{"version"},
		Path: path,
	}

	var b strings.Builder
	_, _, err := cmd.Exec(&b, os.Stderr)
	if err != nil {
		return "", err
	}

	v := b.String()

	v = versionproviders.SplitString(v, " ", 2)

	v = strings.TrimPrefix(v, "go")

	v = strings.TrimSpace(v)

	return v, nil
}
