// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/misspell.json

package misspell

import (
	"errors"
	"os"
	"strings"

	"github.com/stephenwilliams/go-clitools/internal/versionproviders"
	"github.com/stephenwilliams/go-clitools/tools"
)

var MisspellToolInfo = misspellToolInfo{}

type misspellToolInfo struct{}

func (misspellToolInfo) Name() string {
	return "misspell"
}

func (misspellToolInfo) ExecutableName() string {
	return "misspell"
}

// GetVersion returns the version for the tool found with the provided tool provider.
// If tp is nil, the default tool provider is used.
func (i misspellToolInfo) GetVersion(tp tools.ToolProvider) (string, error) {
	if tp != nil {
		// do nothing
	} else if DefaultToolProvider != nil {
		tp = DefaultToolProvider
	} else if tools.DefaultToolProvider != nil {
		tp = tools.DefaultToolProvider
	} else {
		return "", errors.New("no tool provider provided and defaults are nil")
	}

	path, err := tools.ResolveTool(MisspellToolInfo, DefaultToolVersion, tp)
	if err != nil {
		return "", err
	}

	return i.GetVersionWithPath(path)
}

// GetVersionWithPath returns the version for the tool found with the provided path.
// to the tool
func (misspellToolInfo) GetVersionWithPath(path string) (string, error) {
	cmd := &tools.CommandContext{
		Args: []string{"-v"},
		Path: path,
	}

	var b strings.Builder
	_, _, err := cmd.Exec(&b, os.Stderr)
	if err != nil {
		return "", err
	}

	v := b.String()

	v = versionproviders.EqualsReplace(v, "dev", "0.0.0-dev")

	v = strings.TrimSpace(v)

	return v, nil
}
