// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package image

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Sets images and their new names, new tags or digests in the kustomization file
func Image(image string, opts ...ImageOpt) *tools.CommandContext {
	options := &imageOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "set", "image")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, image)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// Sets images and their new names, new tags or digests in the kustomization file
func ImageWithImages(images []string, opts ...ImageOpt) *tools.CommandContext {
	options := &imageOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "set", "image")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, images...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type ImageOpt func(*imageOptions)

func SetToolProvider(p tools.ToolProvider) ImageOpt {
	return func(opts *imageOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) ImageOpt {
	return func(opts *imageOptions) {
		opts.ToolVersion = v
	}
}

type imageOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
}

func (o *imageOptions) toArgs() []string {
	var renderedArgs []string

	return renderedArgs
}
