// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/lefthook.json

package install

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/lefthook"
)

// Write basic configuration file in your project repository. Or initialize existed config
func Install(opts ...InstallOpt) *tools.CommandContext {
	options := &installOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "install")

	_args = append(_args, options.toArgs()...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(lefthook.LefthookToolInfo, defaults.String(options.ToolVersion, lefthook.DefaultToolVersion), options.ToolProvider, lefthook.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type InstallOpt func(*installOptions)

func SetToolProvider(p tools.ToolProvider) InstallOpt {
	return func(opts *installOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) InstallOpt {
	return func(opts *installOptions) {
		opts.ToolVersion = v
	}
}

// remove all hooks from .git/hooks dir and install lefthook hooks
func Aggressive() InstallOpt {
	return func(opts *installOptions) {
		opts.aggressive = ptrhelpers.Bool(true)
	}
}

// reinstall hooks without checking config version
func Force() InstallOpt {
	return func(opts *installOptions) {
		opts.force = ptrhelpers.Bool(true)
	}
}

// disable colored output
func NoColors() InstallOpt {
	return func(opts *installOptions) {
		opts.noColors = ptrhelpers.Bool(true)
	}
}
func Verbose() InstallOpt {
	return func(opts *installOptions) {
		opts.verbose = ptrhelpers.Bool(true)
	}
}

type installOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	aggressive   *bool
	force        *bool
	noColors     *bool
	verbose      *bool
}

func (o *installOptions) toArgs() []string {
	var renderedArgs []string

	if o.aggressive != nil {
		renderedArgs = append(renderedArgs, "--aggressive")
	}

	if o.force != nil {
		renderedArgs = append(renderedArgs, "--aggressive")
	}

	if o.noColors != nil {
		renderedArgs = append(renderedArgs, "--no-colors")
	}

	if o.verbose != nil {
		renderedArgs = append(renderedArgs, "--verbose")
	}

	return renderedArgs
}
