// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/k3d.json

package start

import (
	"fmt"
	"time"

	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/k3d"
)

// Start existing k3d cluster(s)
func Start(opts ...StartOpt) *tools.CommandContext {
	options := &startOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "cluster", "start")

	_args = append(_args, options.toArgs()...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// Start existing k3d cluster(s)
func StartWithName(name string, opts ...StartOpt) *tools.CommandContext {
	options := &startOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "cluster", "start")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, name)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// Start existing k3d cluster(s)
func StartWithNames(names []string, opts ...StartOpt) *tools.CommandContext {
	options := &startOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "cluster", "start")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, names...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type StartOpt func(*startOptions)

func SetToolProvider(p tools.ToolProvider) StartOpt {
	return func(opts *startOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) StartOpt {
	return func(opts *startOptions) {
		opts.ToolVersion = v
	}
}

// Delete all existing clusters
func All() StartOpt {
	return func(opts *startOptions) {
		opts.all = ptrhelpers.Bool(true)
	}
}

// Maximum waiting time for '--wait' before canceling/returning.
func Timeout(value time.Duration) StartOpt {
	return func(opts *startOptions) {
		opts.timeout = &value
	}
}

// Wait for the server(s) (and loadbalancer) to be ready before returning. (default true)
func Wait(value bool) StartOpt {
	return func(opts *startOptions) {
		opts.wait = &value
	}
}

// Enable Log timestamps
func Timestamps() StartOpt {
	return func(opts *startOptions) {
		opts.timestamps = ptrhelpers.Bool(true)
	}
}

// Enable super verbose output (trace logging)
func Trace() StartOpt {
	return func(opts *startOptions) {
		opts.trace = ptrhelpers.Bool(true)
	}
}

// Enable verbose output (debug logging)
func Verbose() StartOpt {
	return func(opts *startOptions) {
		opts.verbose = ptrhelpers.Bool(true)
	}
}

type startOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	all          *bool
	timeout      *time.Duration
	wait         *bool
	timestamps   *bool
	trace        *bool
	verbose      *bool
}

func (o *startOptions) toArgs() []string {
	var renderedArgs []string

	if o.all != nil {
		renderedArgs = append(renderedArgs, "--all")
	}

	if o.timeout != nil {
		renderedArgs = append(renderedArgs, "--timeout", fmt.Sprintf("%v", o.timeout))
	}

	if o.wait != nil {
		renderedArgs = append(renderedArgs, "--wait", fmt.Sprintf("%t", ptrhelpers.BoolValue(o.wait)))
	}

	if o.timestamps != nil {
		renderedArgs = append(renderedArgs, "--timestamps")
	}

	if o.trace != nil {
		renderedArgs = append(renderedArgs, "--trace")
	}

	if o.verbose != nil {
		renderedArgs = append(renderedArgs, "--verbose")
	}

	return renderedArgs
}
