// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package nameprefix

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Sets the value of the namePrefix field in the kustomization file.
func NamePrefix(prefix string, opts ...NamePrefixOpt) *tools.CommandContext {
	options := &nameprefixOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "set", "nameprefix")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, prefix)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type NamePrefixOpt func(*nameprefixOptions)

func SetToolProvider(p tools.ToolProvider) NamePrefixOpt {
	return func(opts *nameprefixOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) NamePrefixOpt {
	return func(opts *nameprefixOptions) {
		opts.ToolVersion = v
	}
}

type nameprefixOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
}

func (o *nameprefixOptions) toArgs() []string {
	var renderedArgs []string

	return renderedArgs
}
