// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/lefthook.json

package lefthook

import (
	"fmt"

	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/tools"
)

var DefaultToolVersion string
var DefaultToolProvider tools.ToolProvider = tools.PathToolProvider{}

func EnsureToolVersion(v string) error {
	if path, err := DefaultToolProvider.GetPath(LefthookToolInfo, defaults.String(v, DefaultToolVersion)); err != nil {
		return err
	} else if path == "" {
		return fmt.Errorf("tool not found with version '%s'", v)
	}

	return nil
}
