// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/lefthook.json

// Fast and powerful Git hooks manager for Node.js, Ruby or any other type of projects.
package lefthook
