// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/k3d.json

package config

import (
	"fmt"

	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/k3d"
)

func Init(opts ...InitOpt) *tools.CommandContext {
	options := &initOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "config", "init")

	_args = append(_args, options.toArgs()...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(k3d.K3dToolInfo, defaults.String(options.ToolVersion, k3d.DefaultToolVersion), options.ToolProvider, k3d.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type InitOpt func(*initOptions)

func SetToolProvider(p tools.ToolProvider) InitOpt {
	return func(opts *initOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) InitOpt {
	return func(opts *initOptions) {
		opts.ToolVersion = v
	}
}

// Force overwrite of target file
func Force() InitOpt {
	return func(opts *initOptions) {
		opts.force = ptrhelpers.Bool(true)
	}
}

// Write a default k3d config (default "k3d-default.yaml")
func Output(value string) InitOpt {
	return func(opts *initOptions) {
		opts.output = &value
	}
}

// Enable Log timestamps
func Timestamps() InitOpt {
	return func(opts *initOptions) {
		opts.timestamps = ptrhelpers.Bool(true)
	}
}

// Enable super verbose output (trace logging)
func Trace() InitOpt {
	return func(opts *initOptions) {
		opts.trace = ptrhelpers.Bool(true)
	}
}

// Enable verbose output (debug logging)
func Verbose() InitOpt {
	return func(opts *initOptions) {
		opts.verbose = ptrhelpers.Bool(true)
	}
}

type initOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
	force        *bool
	output       *string
	timestamps   *bool
	trace        *bool
	verbose      *bool
}

func (o *initOptions) toArgs() []string {
	var renderedArgs []string

	if o.force != nil {
		renderedArgs = append(renderedArgs, "--force")
	}

	if o.output != nil {
		renderedArgs = append(renderedArgs, "--output", fmt.Sprintf("%s", ptrhelpers.StringValue(o.output)))
	}

	if o.timestamps != nil {
		renderedArgs = append(renderedArgs, "--timestamps")
	}

	if o.trace != nil {
		renderedArgs = append(renderedArgs, "--trace")
	}

	if o.verbose != nil {
		renderedArgs = append(renderedArgs, "--verbose")
	}

	return renderedArgs
}
