// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package annotation

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/ptrhelpers"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Removes one or more commonAnnotations from kustomization.yaml
func Annotation(annotation string, opts ...AnnotationOpt) *tools.CommandContext {
	options := &annotationOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "remove", "annotation")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, annotation)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type AnnotationOpt func(*annotationOptions)

func SetToolProvider(p tools.ToolProvider) AnnotationOpt {
	return func(opts *annotationOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) AnnotationOpt {
	return func(opts *annotationOptions) {
		opts.ToolVersion = v
	}
}

// ignore error if the given annotation doesn't exist
func IgnoreNonExistence() AnnotationOpt {
	return func(opts *annotationOptions) {
		opts.ignoreNonExistence = ptrhelpers.Bool(true)
	}
}

// print a stack-trace on error
func StackTrace() AnnotationOpt {
	return func(opts *annotationOptions) {
		opts.stackTrace = ptrhelpers.Bool(true)
	}
}

type annotationOptions struct {
	ToolProvider       tools.ToolProvider
	ToolVersion        string
	ignoreNonExistence *bool
	stackTrace         *bool
}

func (o *annotationOptions) toArgs() []string {
	var renderedArgs []string

	if o.ignoreNonExistence != nil {
		renderedArgs = append(renderedArgs, "--ignore-non-existence")
	}

	if o.stackTrace != nil {
		renderedArgs = append(renderedArgs, "--stack-trace")
	}

	return renderedArgs
}
