// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/kustomize.json

package replicas

import (
	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/tools"
	"github.com/stephenwilliams/go-clitools/tools/kustomize"
)

// Sets replicas count for resources in the kustomization file
func Replicas(replicas string, opts ...ReplicasOpt) *tools.CommandContext {
	options := &replicasOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "set", "label")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, replicas)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

// Sets replicas count for resources in the kustomization file
func ReplicasWithReplices(replicas []string, opts ...ReplicasOpt) *tools.CommandContext {
	options := &replicasOptions{}

	for _, optFunc := range opts {
		optFunc(options)
	}

	var _args []string
	_args = append(_args, "edit", "set", "label")

	_args = append(_args, options.toArgs()...)
	_args = append(_args, replicas...)

	return &tools.CommandContext{
		Args: _args,
		Path: tools.MustResolveTool(kustomize.KustomizeToolInfo, defaults.String(options.ToolVersion, kustomize.DefaultToolVersion), options.ToolProvider, kustomize.DefaultToolProvider, tools.DefaultToolProvider),
	}
}

type ReplicasOpt func(*replicasOptions)

func SetToolProvider(p tools.ToolProvider) ReplicasOpt {
	return func(opts *replicasOptions) {
		opts.ToolProvider = p
	}
}

func SetToolVersion(v string) ReplicasOpt {
	return func(opts *replicasOptions) {
		opts.ToolVersion = v
	}
}

type replicasOptions struct {
	ToolProvider tools.ToolProvider
	ToolVersion  string
}

func (o *replicasOptions) toArgs() []string {
	var renderedArgs []string

	return renderedArgs
}
