// Generated by toolgen. DO NOT EDIT.
// Generated from tool specification:
//   _build/specifications/svu.json

package svu

import (
	"fmt"

	"github.com/stephenwilliams/go-clitools/internal/defaults"
	"github.com/stephenwilliams/go-clitools/tools"
)

var DefaultToolVersion string
var DefaultToolProvider tools.ToolProvider = &tools.ChainToolProvider{Providers: []tools.ToolProvider{
	tools.PathToolProvider{},
	&tools.DownloaderToolProvider{Downloader: GithubReleaseDownloader}}}

func EnsureToolVersion(v string) error {
	if path, err := DefaultToolProvider.GetPath(SVUToolInfo, defaults.String(v, DefaultToolVersion)); err != nil {
		return err
	} else if path == "" {
		return fmt.Errorf("tool not found with version '%s'", v)
	}

	return nil
}
